### ISSUE TITLE
[CI] Full set of checks needed for MeshSync

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshsync#25]
**Current Behavior**
Currently, MeshSync workflows only include lint checks.

**Desired Behavior**
MeshSync workflows are in need of having the full gamut of checks configured.

// @Aisuko, @ramrodo, @shubhank-saxena

**Comment by leecalcote** [comment]
This needs to be done.

**Comment by Aisuko** [comment]
Hi, @leecalcote We use the configuration https://github.com/meshery/meshsync/commit/f5c3f483c1ce5f2da5e64477edce383c75d8b4fe and includes many tools to helps check the code. Do the tools not work well?

**Comment by leecalcote** [comment]
@Aisuko, oh, yes, you're right. I didn't notice that  golangci-lint has been incorporated into workflows here already. I only noticed an issue going stale on a piece of work / workflow that we should have, but missed the fact that we already have such tools in place.

If my understanding is correct, I think we're ok to close this issue. What do you think?

**Comment by leecalcote** [comment]
Thank you, sir, @Aisuko
