### ISSUE TITLE
MeshSync publishing-to: http://localhost:4222

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshsync#26]
**Description**
MeshSync publishing-to: http://localhost:4222 - https://github.com/layer5io/meshsync/blob/f133108ddd96c9a053fbbd10b710002c4cd4aa35/internal/config/config.go#L48

**Expected Behavior**
Should be publishing to the named broker service using kubernetes svc naming.

**Comment by leecalcote** [comment]
Will this service name always be the same? `meshsync.<namespace>.svc.cluster.local`?

**Comment by kumarabd** [comment]
@leecalcote this has been fixed to read the ClusterIP. Also the one you have mentioned is just a default value, it always takes in the value from the CR.
