### ISSUE TITLE
[Docs] The contents in README.md should be replaced

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshsync#27]
**Current State:**

https://github.com/layer5io/meshsync#layer5-repo-template

**Desired State:**

Nowadays, we are going to release a new version meshSync and we can add the contents here.

---
**Contributor Resources**
- [Meshery documentation site](https://meshery.layer5.io/docs/)
- [Meshery documentation source](https://github.com/layer5io/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by leecalcote** [comment]
Good eye, @Aisuko. Yes!

**Comment by Aisuko** [comment]
@weifuchow Would you like to take this one?

**Comment by leecalcote** [comment]
@weifuchow, that would be great. If you do, here's some information about [MeshSync](https://docs.google.com/document/d/1AMi5UTUwLRFeQRQj7YuRQgMG-4IXWie24z4R88Eoazs/edit#heading=h.blih70a9hxp) and it's logo can be found on https://mesheryng.netlify.app/company/brand

**Comment by Aisuko** [comment]
Close due to https://github.com/meshery/meshsync/pull/29
