### ISSUE TITLE
[Docs] Add MeshSync logo to readme

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshsync#3]
**Current State:**
This repo was just created and needs a description of the project.

**Desired State:**
The MeshSync logo and a short blurb about MeshSync should be added to this repo.

---
**Contributor Resources**

- Logo - [meshsync.svg.zip](https://github.com/layer5io/meshsync/files/5697991/meshsync.svg.zip)

**Comment by HarshCasper** [comment]
Hi @leecalcote 

I would like to work on it 💯

**Comment by leecalcote** [comment]
Thanks. That would be great.

**Comment by leecalcote** [comment]
@HarshCasper how are you coming along here? Let me know if I can assist.

**Comment by HarshCasper** [comment]
> @HarshCasper how are you coming along here? Let me know if I can assist.

I will be done within a few hours. Had my University Exams so I couldn't get a chance to take a look at it. Apologies for the same.

**Comment by HarshCasper** [comment]
Issued solved here https://github.com/meshery/meshsync/pull/29

Apologies, I could not deliver it on time

**Comment by leecalcote** [comment]
@HarshCasper, no sweat. There are plenty of other issues that might interest you - https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+label%3A%22help+wanted%22+

**Comment by leecalcote** [comment]
@HarshCasper I don't believe that PR #29 has the logo included in it's update, so this is still an open need.

**Comment by Aisuko** [comment]
> @HarshCasper I don't believe that PR #29 has the logo included in it's update, so this is still an open need.

@leecalcote No problems, sir. But I only saw the meshery-operator logo, I do not know where can find the mesherySync logo? Could you help us? Just comment the logo address would be good. 

Let's finish this @weifuchow
