### ISSUE TITLE
[Brownfield] Annotate discovered resources

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshsync#36]
See https://github.com/layer5io/meshery-operator/issues/84

**Comment by leecalcote** [comment]
Is this included in your latest PR? #38?

**Comment by kumarabd** [comment]
No the annotations are to be dealt with while resource creation I suppose.

**Comment by leecalcote** [comment]
That makes sense for Greenfield (things that Meshery creates), but for Brownfield (existing meshes that Meshery discovers), they will be missing these annotations...

**Comment by leecalcote** [comment]
@kumarabd is this complete?

**Comment by kumarabd** [comment]
@leecalcote  nope this hasn't been addressed yet.
