### ISSUE TITLE
Container crashing on minikube/KIND

### ISSUE THREAD

**Issue by kumarabd** [layer5io/meshsync#37]
**Description**
Fix minikube/KIND cluster specific container issues.
- Roles/Cluster roles need changes

**Screenshots**

**Environment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
@kumarabd fixed?

**Comment by kumarabd** [comment]
Yes it is
