### ISSUE TITLE
[README] Broken images at bottom of readme

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshsync#53]
**Description**
A couple of broken images appear at the bottom of [this repo's readme](https://github.com/layer5io/meshsync#readme).

**Expected Behavior**
These image should be stored and referenced locally in the meshsync repo - https://github.com/layer5io/meshsync/tree/master/.github/readme/images

**Screenshots**
<img width="912" alt="Screen Shot 2021-04-21 at 10 23 48 AM" src="https://user-images.githubusercontent.com/7570704/115579380-bc67b880-a28b-11eb-94cc-de19a3bba278.png">

**Comment by adithyaakrishna** [comment]
@leecalcote Would love to take this up :)

**Comment by theprogrammedwords** [comment]
If this issue is still open, can I take this up?
I am new to making PR.

**Comment by leecalcote** [comment]
@theprogrammedwords good of you to inquire. There was an outstanding PR ready to be merged that fixed this one, but there's more where types like this one comes from. I know that @Ruth-ikegah and @Anita-ihuman will be opening a number of new issues with respect to updating readmes across a number of the repos here.

**Comment by theprogrammedwords** [comment]
Okk sure @leecalcote 
I would look forward to more opportunities. Will keep this on watch. 
Thanks a ton.

**Comment by leecalcote** [comment]
@theprogrammedwords if you haven't joined the Meshery Community, yet, I encourage you to. Please say hi to @Anita-ihuman (and everyone else) when you do. 😄 -- https://meshery.io/community, https://meshery.io/community/newcomers

**Comment by theprogrammedwords** [comment]
Thank you @leecalcote  
I will join the community. Thanks for giving a warm welcome/invite. :)
