### ISSUE TITLE
[Helm chart]: meshsync needs a helm chart

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshsync#7]
**Current Behavior**

**Desired Behavior**

Meshsync needs the helm chart

* It needs to include in the Meshery helm chart.

---
**Resources**

**Alternatives / Additional Context**

**Comment by Aisuko** [comment]
We need a stable image of meshsync.

**Comment by Aisuko** [comment]
Is there anything we lose, I can not find the stable tag for `meshsync` https://hub.docker.com/r/layer5/meshsync/tags?page=1&ordering=last_updated @leecalcote

**Comment by Aisuko** [comment]
Related PR #17

**Comment by leecalcote** [comment]
@Aisuko You’re right - we haven’t made the first stable release of MeshSync, yet, but need to. // @kumarabd

**Comment by kumarabd** [comment]
@Aisuko @leecalcote we don't need a helm chart for MeshSync. The resource is deployed and managed by the operator.

**Comment by leecalcote** [comment]
This is my mistake for having suggested this earlier on.Understanding now that even though MeshSync is it’s own component, it won’t be deployed individually, but under the control of Meshery Operator, we can close this issue.
